import { Alert, Button, Card, Descriptions, Form, Input, List, Modal, Space, Tag, Typography, message } from 'antd';
import { useState } from 'react';
import { apiErrorMessage } from '../../../api/client';
import { ErrorState, LoadingState } from '../../../components/feedback/QueryState';
import { useAccountMutations, useMe, useSessions } from '../hooks/useAuth';

export function AccountPage() {
  const me = useMe(); const sessions = useSessions(); const actions = useAccountMutations(); const [notice, contextHolder] = message.useMessage();
  const [passwordOpen, setPasswordOpen] = useState(false); const [setupOpen, setSetupOpen] = useState(false); const [setupSecret, setSetupSecret] = useState<string>();
  if (me.isLoading) return <LoadingState />;
  if (me.isError || !me.data) return <ErrorState message="Your session may have expired." />;
  const showError = (cause: unknown) => notice.error(apiErrorMessage(cause));
  return <Space direction="vertical" size="large" style={{ width: '100%' }}>{contextHolder}<Typography.Title level={2}>Account security</Typography.Title>
    <Card title="Profile"><Descriptions column={1}><Descriptions.Item label="Name">{me.data.name}</Descriptions.Item><Descriptions.Item label="Email">{me.data.email}</Descriptions.Item><Descriptions.Item label="Time zone">{me.data.timezone}</Descriptions.Item><Descriptions.Item label="Two-factor authentication">{me.data.two_factor_enabled ? <Tag color="green">Enabled</Tag> : <Tag>Not enabled</Tag>}</Descriptions.Item></Descriptions></Card>
    <Card title="Password"><Button onClick={() => setPasswordOpen(true)}>Change password</Button></Card>
    <Card title="Two-factor authentication"><Space>{me.data.two_factor_enabled ? <Button danger onClick={() => Modal.confirm({ title: 'Disable two-factor authentication?', content: <DisableTwoFactorForm onSubmit={async (values) => { try { await actions.disableTwoFactor.mutateAsync(values); notice.success('Two-factor authentication disabled.'); Modal.destroyAll(); } catch (cause) { showError(cause); } }} /> })}>Disable</Button> : <Button type="primary" onClick={() => setSetupOpen(true)}>Set up two-factor authentication</Button>}</Space></Card>
    <Card title="Active sessions">{sessions.isLoading ? <LoadingState /> : sessions.isError ? <Alert type="error" message="Unable to load sessions." /> : <List dataSource={sessions.data} locale={{ emptyText: 'No active sessions.' }} renderItem={(session) => <List.Item actions={[!session.current && <Button danger type="link" key="revoke" onClick={async () => { try { await actions.revokeSession.mutateAsync(session.uuid); notice.success('Session revoked.'); } catch (cause) { showError(cause); } }}>Revoke</Button>] }><List.Item.Meta title={session.current ? 'Current session' : session.ip ?? 'Unknown location'} description={`${session.user_agent ?? 'Unknown device'} · last used ${new Date(session.last_used_at).toLocaleString()}`} /></List.Item>} />}</Card>
    <Modal title="Change password" open={passwordOpen} footer={null} onCancel={() => setPasswordOpen(false)} destroyOnClose><PasswordForm onSubmit={async (values) => { try { await actions.changePassword.mutateAsync(values); notice.success('Password changed.'); setPasswordOpen(false); } catch (cause) { showError(cause); } }} loading={actions.changePassword.isPending} /></Modal>
    <Modal title="Set up two-factor authentication" open={setupOpen} footer={null} onCancel={() => { setSetupOpen(false); setSetupSecret(undefined); }} destroyOnClose>{setupSecret ? <EnableTwoFactorForm secret={setupSecret} onSubmit={async ({ code }) => { try { const result = await actions.enableTwoFactor.mutateAsync(code); Modal.success({ title: 'Save your backup codes', content: <Typography.Paragraph copyable>{result.backup_codes.join('\n')}</Typography.Paragraph> }); setSetupOpen(false); } catch (cause) { showError(cause); } }} /> : <Form layout="vertical" onFinish={async ({ currentPassword }) => { try { const result = await actions.setupTwoFactor.mutateAsync(currentPassword); setSetupSecret(result.secret); } catch (cause) { showError(cause); } }}><Typography.Paragraph>Confirm your password to receive an authenticator secret.</Typography.Paragraph><Form.Item name="currentPassword" label="Current password" rules={[{ required: true }]}><Input.Password /></Form.Item><Button type="primary" htmlType="submit" loading={actions.setupTwoFactor.isPending}>Continue</Button></Form>}</Modal>
  </Space>;
}

function PasswordForm({ onSubmit, loading }: { onSubmit: (values: { currentPassword: string; password: string }) => void; loading: boolean }) { return <Form layout="vertical" onFinish={onSubmit}><Form.Item name="currentPassword" label="Current password" rules={[{ required: true }]}><Input.Password /></Form.Item><Form.Item name="password" label="New password" rules={[{ required: true, min: 12 }]}><Input.Password /></Form.Item><Button type="primary" htmlType="submit" loading={loading}>Change password</Button></Form>; }
function DisableTwoFactorForm({ onSubmit }: { onSubmit: (values: { currentPassword: string; code: string }) => void }) { return <Form layout="vertical" onFinish={onSubmit}><Form.Item name="currentPassword" label="Current password" rules={[{ required: true }]}><Input.Password /></Form.Item><Form.Item name="code" label="Authenticator code" rules={[{ required: true }]}><Input /></Form.Item><Button danger htmlType="submit">Disable two-factor authentication</Button></Form>; }
function EnableTwoFactorForm({ secret, onSubmit }: { secret: string; onSubmit: (values: { code: string }) => void }) { return <Form layout="vertical" onFinish={onSubmit}><Typography.Paragraph>Add this secret to your authenticator app. <Typography.Text copyable strong>{secret}</Typography.Text></Typography.Paragraph><Form.Item name="code" label="Authenticator code" rules={[{ required: true }]}><Input autoComplete="one-time-code" /></Form.Item><Button type="primary" htmlType="submit">Enable</Button></Form>; }
