import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Drawer, Form, Input, Modal, Select, Space, Table, Tag, Typography, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useState } from 'react';
import { apiErrorMessage } from '../../../api/client';
import { action, create, list, read, remove, update, type Brand, type ManagedUser, type Operator, type Permission, type Role } from '../api/adminApi';
import { AdminPage, ServerTable } from '../components/AdminPage';
import { useAdminScope } from '../hooks/useScope';

type BrandForm = { external_id: string; name: string; domains?: string; currencies?: string; lobby_url?: string; default_locale?: string; version?: number };
export function BrandsPage() {
  const { scopePath, me, isPlatform } = useAdminScope(); const client = useQueryClient(); const [notice, holder] = message.useMessage(); const [editing, setEditing] = useState<Brand | null | undefined>(); const [operatorUuid, setOperatorUuid] = useState<string>();
  const operators = useQuery({ queryKey: ['operators-for-brands'], queryFn: () => list<Operator>('/platform/operators', { per_page: 100 }), enabled: isPlatform }); const brandPath = isPlatform ? (operatorUuid ? `/operators/${operatorUuid}` : '') : scopePath;
  const query = useQuery({ queryKey: ['brands', brandPath], queryFn: () => list<Brand>(`${brandPath}/brands`), enabled: Boolean(me.data && brandPath) });
  const save = useMutation({ mutationFn: (value: BrandForm) => { const body = { ...value, domains: value.domains?.split(',').map((entry) => entry.trim()).filter(Boolean), currencies: value.currencies?.split(',').map((entry) => entry.trim()).filter(Boolean) }; return editing ? update<Brand>(`${brandPath}/brands/${editing.uuid}`, body) : create<Brand>(`${brandPath}/brands`, body); }, onSuccess: () => { client.invalidateQueries({ queryKey: ['brands', brandPath] }); setEditing(undefined); notice.success('Brand saved.'); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  const status = useMutation({ mutationFn: ({ uuid, next }: { uuid: string; next: string }) => action<Brand>(`${brandPath}/brands/${uuid}/status`, { status: next }), onSuccess: () => client.invalidateQueries({ queryKey: ['brands', brandPath] }), onError: (error) => notice.error(apiErrorMessage(error)) });
  const columns: ColumnsType<Brand> = [{ title: 'Name', dataIndex: 'name' }, { title: 'External ID', dataIndex: 'external_id' }, { title: 'Currencies', render: (_, row) => row.currencies?.join(', ') ?? 'Inherited' }, { title: 'Status', render: (_, row) => <Tag color={row.status === 'active' ? 'green' : 'default'}>{row.status}</Tag> }, { title: '', render: (_, row) => <Space><Button type="link" onClick={() => setEditing(row)}>Edit</Button><Button type="link" onClick={() => status.mutate({ uuid: row.uuid, next: row.status === 'active' ? 'disabled' : 'active' })}>{row.status === 'active' ? 'Disable' : 'Enable'}</Button></Space> }];
  const initial = editing ? { ...editing, domains: editing.domains.join(','), currencies: editing.currencies?.join(',') } : {};
  return <AdminPage title="Brands" actions={<Button type="primary" disabled={!brandPath} onClick={() => setEditing(null)}>Add brand</Button>}>{holder}{isPlatform && <Select placeholder="Choose an operator" style={{ width: 320, marginBottom: 16 }} value={operatorUuid} onChange={setOperatorUuid} options={(operators.data?.items ?? []).map((operator) => ({ value: operator.uuid, label: operator.name }))} />}{!brandPath ? <Typography.Text>Select an operator to manage its brands.</Typography.Text> : <><ServerTable page={query.data} loading={query.isLoading} error={query.error} columns={columns} /><Drawer title={editing ? 'Edit brand' : 'Add brand'} open={editing !== undefined} onClose={() => setEditing(undefined)} destroyOnClose><Form<BrandForm> key={editing?.uuid ?? 'new'} layout="vertical" initialValues={initial} onFinish={(v) => save.mutate(editing ? { ...v, version: editing.version } : v)}><Form.Item label="External ID" name="external_id" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="Name" name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="Domains (comma-separated)" name="domains"><Input /></Form.Item><Form.Item label="Currencies (comma-separated; omit to inherit)" name="currencies"><Input /></Form.Item><Form.Item label="Lobby URL" name="lobby_url"><Input /></Form.Item><Form.Item label="Default locale" name="default_locale"><Input /></Form.Item><Button type="primary" htmlType="submit" loading={save.isPending}>Save</Button></Form></Drawer></>}</AdminPage>;
}

type RoleForm = { name: string; description?: string; permissions: string[]; version?: number };
export function RolesPage() {
  const { scopePath, me } = useAdminScope(); const client = useQueryClient(); const [notice, holder] = message.useMessage(); const [editing, setEditing] = useState<Role | null | undefined>();
  const roleQuery = useQuery({ queryKey: ['roles', scopePath], queryFn: () => read<Role[]>(`${scopePath}/roles`), enabled: Boolean(me.data) });
  const permissions = useQuery({ queryKey: ['permissions', me.data?.operator_uuid], queryFn: () => read<Permission[]>(`/permissions?scope=${me.data?.operator_uuid ? 'operator' : 'platform'}`), enabled: Boolean(me.data) });
  const save = useMutation({ mutationFn: (value: RoleForm) => editing ? update<Role>(`${scopePath}/roles/${editing.uuid}`, value) : create<Role>(`${scopePath}/roles`, value), onSuccess: () => { client.invalidateQueries({ queryKey: ['roles', scopePath, 'get'] }); setEditing(undefined); notice.success('Role saved.'); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  const destroy = useMutation({ mutationFn: (uuid: string) => remove(`${scopePath}/roles/${uuid}`), onSuccess: () => client.invalidateQueries({ queryKey: ['roles', scopePath, 'get'] }), onError: (error) => notice.error(apiErrorMessage(error)) });
  const columns: ColumnsType<Role> = [{ title: 'Name', dataIndex: 'name' }, { title: 'Scope', dataIndex: 'scope' }, { title: 'Permissions', render: (_, row) => row.permissions.length }, { title: 'Assigned users', dataIndex: 'users_count' }, { title: '', render: (_, row) => <Space><Button type="link" onClick={() => setEditing(row)}>View / edit</Button>{!row.is_system && <Button danger type="link" onClick={() => Modal.confirm({ title: 'Delete this role?', onOk: () => destroy.mutateAsync(row.uuid) })}>Delete</Button>}</Space> }];
  return <AdminPage title="Roles" actions={<Button type="primary" onClick={() => setEditing(null)}>Create role</Button>}>{holder}<ServerTable page={roleQuery.data ? { items: roleQuery.data, page: 1, perPage: roleQuery.data.length, total: roleQuery.data.length, totalPages: 1 } : undefined} loading={roleQuery.isLoading} error={roleQuery.error} columns={columns} /><Drawer title={editing ? 'Role' : 'Create role'} open={editing !== undefined} onClose={() => setEditing(undefined)} destroyOnClose width={560}><Form<RoleForm> key={editing?.uuid ?? 'new'} layout="vertical" initialValues={editing ?? { permissions: [] }} onFinish={(value) => save.mutate(editing ? { ...value, version: editing.version } : value)}><Form.Item label="Name" name="name" rules={[{ required: true }]}><Input disabled={editing?.is_system} /></Form.Item><Form.Item label="Description" name="description"><Input /></Form.Item><Form.Item label="Permissions" name="permissions" rules={[{ required: true }]}><Select mode="multiple" options={(permissions.data ?? []).map((permission) => ({ value: permission.slug, label: `${permission.group}: ${permission.description}` }))} disabled={editing?.is_system} /></Form.Item>{!editing?.is_system && <Button type="primary" htmlType="submit" loading={save.isPending}>Save</Button>}</Form></Drawer></AdminPage>;
}

type UserForm = { email?: string; name: string; locale?: string; role_uuids: string[]; brand_uuids?: string[]; version?: number };
export function UsersPage() {
  const { scopePath, me } = useAdminScope(); const client = useQueryClient(); const [notice, holder] = message.useMessage(); const [editing, setEditing] = useState<ManagedUser | null | undefined>();
  const query = useQuery({ queryKey: ['users', scopePath], queryFn: () => list<ManagedUser>(`${scopePath}/users`), enabled: Boolean(me.data) });
  const roles = useQuery({ queryKey: ['roles-for-users', scopePath], queryFn: () => read<Role[]>(`${scopePath}/roles`), enabled: Boolean(me.data) });
  const save = useMutation({ mutationFn: (value: UserForm) => editing ? update<ManagedUser>(`${scopePath}/users/${editing.uuid}`, value) : create<ManagedUser>(`${scopePath}/users`, value), onSuccess: () => { client.invalidateQueries({ queryKey: ['users', scopePath] }); setEditing(undefined); notice.success(editing ? 'User updated.' : 'Invitation sent.'); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  const userAction = useMutation({ mutationFn: ({ uuid, verb }: { uuid: string; verb: string }) => action<ManagedUser>(`${scopePath}/users/${uuid}/${verb}`), onSuccess: () => client.invalidateQueries({ queryKey: ['users', scopePath] }), onError: (error) => notice.error(apiErrorMessage(error)) });
  const destroy = useMutation({ mutationFn: (uuid: string) => remove(`${scopePath}/users/${uuid}`), onSuccess: () => client.invalidateQueries({ queryKey: ['users', scopePath] }), onError: (error) => notice.error(apiErrorMessage(error)) });
  const columns: ColumnsType<ManagedUser> = [{ title: 'Name', dataIndex: 'name' }, { title: 'Email', dataIndex: 'email' }, { title: 'Roles', render: (_, row) => row.roles.map((role) => role.name).join(', ') }, { title: 'Status', render: (_, row) => <Tag color={row.status === 'active' ? 'green' : row.status === 'blocked' ? 'red' : 'orange'}>{row.status}</Tag> }, { title: '2FA', render: (_, row) => row.two_factor_enabled ? 'Enabled' : '—' }, { title: '', render: (_, row) => <Space><Button type="link" onClick={() => setEditing(row)}>Edit</Button>{row.status === 'invited' && <Button type="link" onClick={() => userAction.mutate({ uuid: row.uuid, verb: 'resend-invitation' })}>Resend</Button>}<Button type="link" onClick={() => userAction.mutate({ uuid: row.uuid, verb: row.status === 'blocked' ? 'unblock' : 'block' })}>{row.status === 'blocked' ? 'Unblock' : 'Block'}</Button><Button type="link" onClick={() => userAction.mutate({ uuid: row.uuid, verb: 'reset-2fa' })}>Reset 2FA</Button><Button type="link" onClick={() => userAction.mutate({ uuid: row.uuid, verb: 'logout' })}>Log out</Button><Button danger type="link" onClick={() => Modal.confirm({ title: 'Delete this user?', onOk: () => destroy.mutateAsync(row.uuid) })}>Delete</Button></Space> }];
  return <AdminPage title="Users" actions={<Button type="primary" onClick={() => setEditing(null)}>Invite user</Button>}>{holder}<ServerTable page={query.data} loading={query.isLoading} error={query.error} columns={columns} /><Drawer title={editing ? 'Edit user' : 'Invite user'} open={editing !== undefined} onClose={() => setEditing(undefined)} destroyOnClose><Form<UserForm> key={editing?.uuid ?? 'new'} layout="vertical" initialValues={editing ? { ...editing, role_uuids: editing.roles.map((role) => role.uuid) } : { locale: 'en', role_uuids: [] }} onFinish={(value) => save.mutate(editing ? { ...value, version: editing.version } : value)}>{!editing && <Form.Item label="Email" name="email" rules={[{ required: true, type: 'email' }]}><Input /></Form.Item>}<Form.Item label="Name" name="name" rules={[{ required: true }]}><Input /></Form.Item>{!editing && <Form.Item label="Locale" name="locale"><Input /></Form.Item>}<Form.Item label="Roles" name="role_uuids" rules={[{ required: true }]}><Select mode="multiple" options={(roles.data ?? []).map((role) => ({ value: role.uuid, label: role.name }))} /></Form.Item><Form.Item label="Brand access UUIDs (optional)" name="brand_uuids"><Select mode="tags" tokenSeparators={[',']} /></Form.Item><Button type="primary" htmlType="submit" loading={save.isPending}>Save</Button></Form></Drawer></AdminPage>;
}

type ProfileForm = { timezone: string; reporting_currency: string; contacts?: string; version?: number };
export function OperatorProfilePage() {
  const { scopePath, me, isPlatform } = useAdminScope(); const client = useQueryClient(); const [notice, holder] = message.useMessage();
  const profile = useQuery({ queryKey: ['operator-profile', scopePath], queryFn: () => read<Record<string, unknown>>(`${scopePath}/profile`), enabled: Boolean(me.data && !isPlatform) });
  const integration = useQuery({ queryKey: ['operator-integration', scopePath], queryFn: () => read<Record<string, unknown>>(`${scopePath}/integration`), enabled: Boolean(me.data && !isPlatform) });
  const save = useMutation({ mutationFn: (value: ProfileForm) => update<Record<string, unknown>>(`${scopePath}/profile`, { version: profile.data?.version, timezone: value.timezone, reporting_currency: value.reporting_currency, contacts: value.contacts ? JSON.parse(value.contacts) as Record<string, string> : {} }), onSuccess: () => { client.invalidateQueries({ queryKey: ['operator-profile', scopePath] }); notice.success('Profile saved.'); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  if (isPlatform) return <AdminPage title="Operator profile"><Typography.Text>Select an operator through the Operators page to inspect its platform-managed settings.</Typography.Text></AdminPage>;
  return <AdminPage title="Operator profile">{holder}<Form<ProfileForm> layout="vertical" initialValues={profile.data ? { timezone: profile.data.timezone, reporting_currency: profile.data.reporting_currency, contacts: JSON.stringify(profile.data.contacts ?? {}, null, 2) } : undefined} onFinish={(value) => save.mutate(value)}><Form.Item label="Timezone" name="timezone" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="Reporting currency" name="reporting_currency" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="Contacts (JSON)" name="contacts"><Input.TextArea rows={5} /></Form.Item><Button type="primary" htmlType="submit" loading={save.isPending}>Save profile</Button></Form><Typography.Title level={4}>Integration</Typography.Title><Table dataSource={integration.data ? Object.entries(integration.data).map(([key, value]) => ({ key, value: typeof value === 'string' ? value : JSON.stringify(value) })) : []} columns={[{ title: 'Setting', dataIndex: 'key' }, { title: 'Value', dataIndex: 'value' }]} loading={integration.isLoading} pagination={false} /></AdminPage>;
}
