import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Drawer, Form, Input, InputNumber, Modal, Select, Space, Switch, Table, Tag, Typography, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useState } from 'react';
import { apiErrorMessage } from '../../../api/client';
import { action, adminApi, create, list, read, remove, update, type Credential, type Currency, type Operator, type ProviderInstance } from '../api/adminApi';
import { AdminPage, ReloadButton, ServerTable } from '../components/AdminPage';

const TIMEZONE_OPTIONS = [
  'UTC', 'Europe/London', 'Europe/Berlin', 'Europe/Paris', 'Europe/Istanbul',
  'Asia/Dubai', 'Asia/Tbilisi', 'Asia/Kolkata', 'Asia/Bangkok', 'Asia/Singapore', 'Asia/Tokyo',
  'America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles', 'America/Sao_Paulo',
  'Africa/Cairo', 'Africa/Johannesburg', 'Australia/Sydney', 'Pacific/Auckland',
].map((value) => ({ value, label: value }));

const LOCALE_OPTIONS = [
  { value: 'en', label: 'English (en)' }, { value: 'ru', label: 'Russian (ru)' },
  { value: 'ka', label: 'Georgian (ka)' }, { value: 'tr', label: 'Turkish (tr)' },
  { value: 'de', label: 'German (de)' }, { value: 'es', label: 'Spanish (es)' },
  { value: 'fr', label: 'French (fr)' }, { value: 'pt', label: 'Portuguese (pt)' },
];

export function ProviderInstancesPage() {
  const query = useQuery({ queryKey: ['provider-instances'], queryFn: adminApi.providerInstances });
  const columns: ColumnsType<ProviderInstance> = [{ title: 'Name', dataIndex: 'name' }, { title: 'Code', dataIndex: 'code' }, { title: 'Type', dataIndex: 'type' }, { title: 'Jurisdiction', dataIndex: 'jurisdiction' }, { title: 'Operators', dataIndex: 'operators_count' }, { title: 'Status', render: (_, row) => <Tag color={row.status === 'active' ? 'green' : 'default'}>{row.status}</Tag> }];
  if (query.isLoading) return <AdminPage title="Provider instances"><Typography.Text>Loading…</Typography.Text></AdminPage>;
  return <AdminPage title="Provider instances" actions={<ReloadButton onClick={() => query.refetch()} />}><Table rowKey="uuid" columns={columns} dataSource={query.data ?? []} loading={query.isFetching} /></AdminPage>;
}

type CurrencyForm = { code?: string; name: string; symbol?: string; units: number; is_crypto?: boolean; is_active?: boolean; version?: number };
export function CurrenciesPage() {
  const client = useQueryClient(); const [notice, holder] = message.useMessage(); const [editing, setEditing] = useState<Currency | null | undefined>();
  const query = useQuery({ queryKey: ['currencies'], queryFn: () => adminApi.currencies() });
  const save = useMutation({ mutationFn: async (values: CurrencyForm) => editing ? update<Currency>(`/platform/currencies/${editing.code}`, values as unknown as Record<string, unknown>) : create<Currency>('/platform/currencies', values as unknown as Record<string, unknown>), onSuccess: () => { client.invalidateQueries({ queryKey: ['currencies'] }); setEditing(undefined); notice.success('Currency saved.'); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  const columns: ColumnsType<Currency> = [{ title: 'Code', dataIndex: 'code' }, { title: 'Name', dataIndex: 'name' }, { title: 'Symbol', dataIndex: 'symbol' }, { title: 'Units', dataIndex: 'units' }, { title: 'Type', render: (_, row) => row.is_crypto ? 'Crypto' : 'Fiat' }, { title: 'Status', render: (_, row) => <Tag color={row.is_active ? 'green' : 'default'}>{row.is_active ? 'active' : 'inactive'}</Tag> }, { title: '', render: (_, row) => <Button type="link" onClick={() => setEditing(row)}>Edit</Button> }];
  return <AdminPage title="Currencies" actions={<Space><ReloadButton onClick={() => query.refetch()} /><Button type="primary" onClick={() => setEditing(null)}>Add currency</Button></Space>}>{holder}<Table rowKey="code" columns={columns} dataSource={query.data ?? []} loading={query.isLoading} pagination={false} /><Drawer title={editing ? `Edit ${editing.code}` : 'Add currency'} open={editing !== undefined} onClose={() => setEditing(undefined)} destroyOnClose><Form<CurrencyForm> layout="vertical" initialValues={editing ?? { units: 2, is_crypto: false, is_active: true }} onFinish={(values) => save.mutate(values)}><Form.Item hidden name="version"><Input /></Form.Item>{!editing && <Form.Item label="Code" name="code" rules={[{ required: true }]}><Input /></Form.Item>}<Form.Item label="Name" name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="Symbol" name="symbol"><Input /></Form.Item><Form.Item label="Minor units" name="units" rules={[{ required: true }]}><InputNumber min={0} max={8} style={{ width: '100%' }} /></Form.Item>{editing ? <Form.Item label="Active" name="is_active" valuePropName="checked"><Switch /></Form.Item> : <Form.Item label="Cryptocurrency" name="is_crypto" valuePropName="checked"><Switch /></Form.Item>}<Button htmlType="submit" type="primary" loading={save.isPending}>Save</Button></Form></Drawer></AdminPage>;
}

type OperatorForm = { name: string; legal_name?: string; server_id?: string; provider_instance?: string; wallet_url?: string; wallet_timeout_ms?: number; wallet_connect_timeout_ms?: number; lobby_url?: string; deposit_url?: string; default_locale?: string; reporting_currency: string; currencies: string; timezone?: string; is_test?: boolean; demo_enabled?: boolean; require_2fa?: boolean; version?: number };
export function OperatorsPage() {
  const client = useQueryClient(); const [notice, holder] = message.useMessage(); const [editing, setEditing] = useState<Operator | null | undefined>(); const [credentialsFor, setCredentialsFor] = useState<Operator>();
  const query = useQuery({ queryKey: ['operators'], queryFn: () => list<Operator>('/platform/operators') }); const instances = useQuery({ queryKey: ['provider-instances'], queryFn: adminApi.providerInstances }); const currencies = useQuery({ queryKey: ['currencies'], queryFn: () => adminApi.currencies(true) });
  const save = useMutation({ mutationFn: (value: OperatorForm) => { const body = { ...value, currencies: value.currencies.split(',').map((v) => v.trim()).filter(Boolean) }; return editing ? update<Operator>(`/platform/operators/${editing.uuid}`, body) : create<Operator>('/platform/operators', body); }, onSuccess: () => { client.invalidateQueries({ queryKey: ['operators'] }); setEditing(undefined); notice.success('Operator saved.'); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  const status = useMutation({ mutationFn: ({ uuid, next }: { uuid: string; next: string }) => create<Operator>(`/platform/operators/${uuid}/status`, { status: next }), onSuccess: () => client.invalidateQueries({ queryKey: ['operators'] }), onError: (error) => notice.error(apiErrorMessage(error)) });
  const columns: ColumnsType<Operator> = [{ title: 'Name', dataIndex: 'name' }, { title: 'Server ID', dataIndex: 'server_id' }, { title: 'Instance', render: (_, row) => row.provider_instance.code }, { title: 'Currencies', render: (_, row) => row.currencies.join(', ') }, { title: 'Brands', dataIndex: 'brands_count' }, { title: 'Status', render: (_, row) => <Tag color={row.status === 'active' ? 'green' : 'orange'}>{row.status}</Tag> }, { title: 'Actions', render: (_, row) => <Space><Button type="link" onClick={() => setEditing(row)}>Edit</Button><Button type="link" onClick={() => setCredentialsFor(row)}>Keys</Button><Button type="link" onClick={() => status.mutate({ uuid: row.uuid, next: row.status === 'active' ? 'suspended' : 'active' })}>{row.status === 'active' ? 'Suspend' : 'Activate'}</Button></Space> }];
  const initial = editing ? { ...editing, provider_instance: editing.provider_instance.code, currencies: editing.currencies.join(',') } : { currencies: '', timezone: 'UTC', default_locale: 'en', demo_enabled: true };
  return <AdminPage title="Operators" actions={<Button type="primary" onClick={() => setEditing(null)}>Add operator</Button>}>{holder}<ServerTable page={query.data} loading={query.isLoading} error={query.error} columns={columns} onChange={(page) => client.invalidateQueries({ queryKey: ['operators', page] })} /><Drawer title={editing ? 'Edit operator' : 'Add operator'} open={editing !== undefined} onClose={() => setEditing(undefined)} destroyOnClose width={560}><Typography.Paragraph type="secondary">To activate an operator, configure a wallet URL and create an active wallet-signing key from the Keys action.</Typography.Paragraph><Form<OperatorForm> key={editing?.uuid ?? 'new'} layout="vertical" initialValues={initial} onFinish={(v) => save.mutate(editing ? { ...v, version: editing.version } : v)}><Form.Item label="Name" name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="Legal name" name="legal_name"><Input /></Form.Item><Form.Item label="Server ID" name="server_id"><Input /></Form.Item><Form.Item label="Provider instance" name="provider_instance"><Select options={(instances.data ?? []).map((item) => ({ value: item.code, label: item.name }))} /></Form.Item><Typography.Title level={5}>Wallet integration</Typography.Title><Form.Item label="Wallet URL" name="wallet_url" rules={[{ type: 'url', message: 'Enter a valid URL.' }]}><Input placeholder="https://casino.example.com/wallet" /></Form.Item><Space style={{ width: '100%' }}><Form.Item label="Wallet timeout (ms)" name="wallet_timeout_ms"><InputNumber min={500} max={60000} /></Form.Item><Form.Item label="Connect timeout (ms)" name="wallet_connect_timeout_ms"><InputNumber min={500} max={60000} /></Form.Item></Space><Form.Item label="Lobby URL" name="lobby_url" rules={[{ type: 'url' }]}><Input /></Form.Item><Form.Item label="Deposit URL" name="deposit_url" rules={[{ type: 'url' }]}><Input /></Form.Item><Form.Item label="Currencies (comma-separated)" name="currencies" rules={[{ required: true }]}><Input placeholder={(currencies.data ?? []).map((currency) => currency.code).join(', ')} /></Form.Item><Form.Item label="Reporting currency" name="reporting_currency" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="Timezone" name="timezone" rules={[{ required: true }]}><Select showSearch options={TIMEZONE_OPTIONS} /></Form.Item><Form.Item label="Default locale" name="default_locale" rules={[{ required: true }]}><Select options={LOCALE_OPTIONS} /></Form.Item><Form.Item label="Test operator" name="is_test" valuePropName="checked"><Switch /></Form.Item><Form.Item label="Demo enabled" name="demo_enabled" valuePropName="checked"><Switch /></Form.Item><Form.Item label="Require 2FA" name="require_2fa" valuePropName="checked"><Switch /></Form.Item><Button type="primary" htmlType="submit" loading={save.isPending}>Save</Button></Form></Drawer>{credentialsFor && <CredentialsModal operator={credentialsFor} close={() => setCredentialsFor(undefined)} />}</AdminPage>;
}

function CredentialsModal({ operator, close }: { operator: Operator; close: () => void }) {
  const client = useQueryClient(); const [notice, holder] = message.useMessage(); const [secret, setSecret] = useState<string>(); const query = useQuery({ queryKey: ['credentials', operator.uuid], queryFn: () => read<Credential[]>(`/platform/operators/${operator.uuid}/credentials`) });
  const generate = useMutation({ mutationFn: (purpose: string) => create<Credential & { secret: string }>(`/platform/operators/${operator.uuid}/credentials`, { purpose }), onSuccess: (data) => { setSecret(data.secret); client.invalidateQueries({ queryKey: ['credentials', operator.uuid] }); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  const rotate = useMutation({ mutationFn: (uuid: string) => action<Credential & { secret: string }>(`/platform/operators/${operator.uuid}/credentials/${uuid}/rotate`), onSuccess: (data) => { setSecret(data.secret); client.invalidateQueries({ queryKey: ['credentials', operator.uuid] }); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  const revoke = useMutation({ mutationFn: (uuid: string) => remove(`/platform/operators/${operator.uuid}/credentials/${uuid}`), onSuccess: () => client.invalidateQueries({ queryKey: ['credentials', operator.uuid] }) });
  return <Modal open title={`${operator.name}: credentials`} onCancel={close} footer={null} width={720}>{holder}{secret && <Typography.Paragraph type="danger">Copy this secret now; it will not be shown again. <Typography.Text copyable>{secret}</Typography.Text></Typography.Paragraph>}<Space><Button onClick={() => generate.mutate('wallet_signing')}>Create wallet-signing key</Button><Button onClick={() => generate.mutate('api_inbound')}>Create inbound API key</Button></Space><Table rowKey="uuid" pagination={false} loading={query.isLoading} dataSource={query.data ?? []} columns={[{ title: 'Purpose', dataIndex: 'purpose' }, { title: 'Key ID', dataIndex: 'key_id' }, { title: 'Status', dataIndex: 'status' }, { title: 'Last used', dataIndex: 'last_used_at' }, { title: '', render: (_, row: Credential) => <Space><Button type="link" onClick={() => rotate.mutate(row.uuid)}>Rotate</Button><Button danger type="link" onClick={() => Modal.confirm({ title: 'Revoke this credential?', onOk: () => revoke.mutateAsync(row.uuid) })}>Revoke</Button></Space> }]} /></Modal>;
}
