import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Button, Drawer, Form, Input, InputNumber, Select, Space, Switch, Table, Tag, Typography, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useMemo, useState } from 'react';
import { apiErrorMessage } from '../../../api/client';
import { action, adminApi, create, list, read, update, type AnalyticsSummary, type AuditEntry, type Game, type TimeseriesPoint } from '../api/adminApi';
import { AdminPage, ServerTable } from '../components/AdminPage';
import { useAdminScope } from '../hooks/useScope';

export function GamesPage() {
  const { scopePath, isPlatform, me } = useAdminScope(); const client = useQueryClient(); const [notice, holder] = message.useMessage(); const [selected, setSelected] = useState<Game>(); const [creating, setCreating] = useState(false);
  const path = `${scopePath}/games`; const query = useQuery({ queryKey: ['games', path], queryFn: () => list<Game>(path), enabled: Boolean(me.data) });
  const save = useMutation({ mutationFn: ({ uuid, suffix, body }: { uuid: string; suffix: string; body: Record<string, unknown> }) => update<Game>(`/platform/games/${uuid}${suffix}`, body), onSuccess: (game) => { setSelected(game); client.invalidateQueries({ queryKey: ['games', path] }); notice.success('Game configuration saved.'); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  const createGame = useMutation({ mutationFn: (body: Record<string, unknown>) => create<Game>('/platform/games', body), onSuccess: (game) => { client.invalidateQueries({ queryKey: ['games', path] }); setCreating(false); setSelected(game); notice.success('Game created as a draft. Configure its limits before activating it.'); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  const status = useMutation({ mutationFn: ({ uuid, value, comment }: { uuid: string; value: string; comment: string }) => action<Game>(`/platform/games/${uuid}/status`, { status: value, comment }), onSuccess: (game) => { setSelected(game); client.invalidateQueries({ queryKey: ['games', path] }); notice.success('Game status updated.'); }, onError: (error) => notice.error(apiErrorMessage(error)) });
  const columns: ColumnsType<Game> = [{ title: 'Title', dataIndex: 'title' }, { title: 'Identifier', dataIndex: 'identifier' }, { title: 'Category', dataIndex: 'category' }, { title: 'Genre', dataIndex: 'genre' }, { title: 'Status', render: (_, row) => <Tag color={row.status === 'active' ? 'green' : row.status === 'disabled' ? 'red' : 'default'}>{row.status}</Tag> }, { title: '', render: (_, row) => <Button type="link" onClick={() => setSelected(row)}>{isPlatform ? 'Configure' : 'View'}</Button> }];
  return <AdminPage title={isPlatform ? 'Game catalog' : 'Game catalog'} actions={isPlatform ? <Button type="primary" onClick={() => setCreating(true)}>Create game</Button> : undefined}>{holder}<ServerTable page={query.data} loading={query.isLoading} error={query.error} columns={columns} /><Drawer width={650} title={selected?.title} open={Boolean(selected)} onClose={() => setSelected(undefined)}>{selected && <GameDetails game={selected} canManage={isPlatform} saveStatus={(value, comment) => status.mutate({ uuid: selected.uuid, value, comment })} saveConfiguration={(suffix, body) => save.mutate({ uuid: selected.uuid, suffix, body })} />}</Drawer><Drawer width={560} title="Create game" open={creating} onClose={() => setCreating(false)} destroyOnClose><CreateGameForm submitting={createGame.isPending} onSubmit={(body) => createGame.mutate(body)} /></Drawer></AdminPage>;
}

type NewGame = { identifier: string; genre: string; title: string; category: string; devices: string[]; api_freespins?: boolean; in_game_freespins?: boolean; has_buy_bonus?: boolean; rtp_theoretical?: number; volatility?: string; max_win_multiplier?: number; paylines?: number; release_date?: string; description?: string; tags?: string[] };
function CreateGameForm({ submitting, onSubmit }: { submitting: boolean; onSubmit: (body: Record<string, unknown>) => void }) {
  return <Form<NewGame> layout="vertical" initialValues={{ genre: 'slot', category: 'slots', devices: ['desktop', 'mobile'], api_freespins: false, in_game_freespins: false, has_buy_bonus: false, tags: [] }} onFinish={(values) => onSubmit(values)}><Form.Item label="Identifier" name="identifier" rules={[{ required: true, pattern: /^[A-Za-z0-9][A-Za-z0-9_-]{1,62}[A-Za-z0-9]$/, message: 'Use 3–64 letters, digits, hyphens, or underscores.' }]}><Input /></Form.Item><Form.Item label="Game engine genre" name="genre" rules={[{ required: true }]}><Select options={[{ value: 'slot', label: 'Slot' }, { value: 'instant_win', label: 'Instant win' }]} /></Form.Item><Form.Item label="Title" name="title" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="Catalog category" name="category" rules={[{ required: true }]}><Select options={[{ value: 'slots', label: 'Slots' }, { value: 'instant', label: 'Instant' }]} /></Form.Item><Form.Item label="Supported devices" name="devices" rules={[{ required: true }]}><Select mode="multiple" options={['desktop', 'mobile', 'tablet'].map((value) => ({ value }))} /></Form.Item><Form.Item label="Theoretical RTP" name="rtp_theoretical"><Input type="number" min="0" max="100" step="0.001" /></Form.Item><Form.Item label="Volatility" name="volatility"><Select allowClear options={['low', 'medium', 'high', 'very_high'].map((value) => ({ value }))} /></Form.Item><Form.Item label="Maximum win multiplier" name="max_win_multiplier"><Input type="number" min="1" /></Form.Item><Form.Item label="Paylines" name="paylines"><Input type="number" min="1" /></Form.Item><Form.Item label="Release date" name="release_date"><Input type="date" /></Form.Item><Form.Item label="Description" name="description"><Input.TextArea rows={3} /></Form.Item><Form.Item label="Tags" name="tags"><Select mode="tags" tokenSeparators={[',']} /></Form.Item><Form.Item label="API freespins" name="api_freespins" valuePropName="checked"><Switch /></Form.Item><Form.Item label="In-game freespins" name="in_game_freespins" valuePropName="checked"><Switch /></Form.Item><Form.Item label="Buy bonus" name="has_buy_bonus" valuePropName="checked"><Switch /></Form.Item><Button type="primary" htmlType="submit" loading={submitting}>Create draft game</Button></Form>;
}

function GameDetails({ game, canManage, saveStatus, saveConfiguration }: { game: Game; canManage: boolean; saveStatus: (status: string, comment: string) => void; saveConfiguration: (suffix: string, body: Record<string, unknown>) => void }) {
  const devices = Array.isArray(game.devices) ? game.devices.join(', ') : '';
  return <Space direction="vertical" size="middle" style={{ width: '100%' }}><Typography.Paragraph><strong>Identifier:</strong> {game.identifier}</Typography.Paragraph><Typography.Paragraph><strong>Genre:</strong> {game.genre}</Typography.Paragraph><Typography.Paragraph><strong>Supported currencies:</strong> {game.currencies.map((currency) => String(currency.currency)).join(', ') || 'None'}</Typography.Paragraph>{canManage && <>
    <Typography.Title level={4}>Status</Typography.Title><Form layout="vertical" onFinish={(values: { status: string; comment: string }) => saveStatus(values.status, values.comment)} initialValues={{ status: game.status }}><Form.Item label="Status" name="status" rules={[{ required: true }]}><Select options={['draft', 'active', 'disabled', 'retired'].map((value) => ({ value }))} /></Form.Item><Form.Item label="Audit comment" name="comment" rules={[{ required: true, min: 3 }]}><Input.TextArea /></Form.Item><Button type="primary" htmlType="submit">Update status</Button></Form>
    <Typography.Title level={4}>Catalog metadata</Typography.Title><Form layout="vertical" initialValues={{ title: game.title, category: game.category, devices, api_freespins: Boolean(game.api_freespins), in_game_freespins: Boolean(game.in_game_freespins), has_buy_bonus: Boolean(game.has_buy_bonus) }} onFinish={(values: { title: string; category: string; devices: string; api_freespins: boolean; in_game_freespins: boolean; has_buy_bonus: boolean }) => saveConfiguration('', { version: game.version, title: values.title, category: values.category, devices: values.devices.split(',').map((value) => value.trim()).filter(Boolean), api_freespins: values.api_freespins, in_game_freespins: values.in_game_freespins, has_buy_bonus: values.has_buy_bonus })}><Form.Item label="Title" name="title" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="Category" name="category" rules={[{ required: true }]}><Select options={['slots', 'instant'].map((value) => ({ value }))} /></Form.Item><Form.Item label="Devices (comma-separated)" name="devices" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="API freespins" name="api_freespins" valuePropName="checked"><Switch /></Form.Item><Form.Item label="In-game freespins" name="in_game_freespins" valuePropName="checked"><Switch /></Form.Item><Form.Item label="Buy bonus" name="has_buy_bonus" valuePropName="checked"><Switch /></Form.Item><Button htmlType="submit">Save metadata</Button></Form>
    <CurrencyLimitsForm initial={game.currencies} onSave={(currencies) => saveConfiguration('/currencies', { version: game.version, currencies })} />
    <BetLevelsForm initial={game.bet_levels} onSave={(bet_levels) => saveConfiguration('/bet-levels', { version: game.version, bet_levels })} />
    <WinThresholdsForm initial={game.win_thresholds} onSave={(win_thresholds) => saveConfiguration('/win-thresholds', { version: game.version, win_thresholds })} />
  </>}</Space>;
}

type CurrencyLimit = { currency: string; bet_min: number; bet_max: number; bet_default: number; bet_step?: number };
function CurrencyLimitsForm({ initial, onSave }: { initial: unknown; onSave: (currencies: CurrencyLimit[]) => void }) {
  const currencies = useQuery({ queryKey: ['active-currencies'], queryFn: () => adminApi.currencies(true) });
  return <><Typography.Title level={4}>Currencies and bet limits</Typography.Title><Typography.Paragraph type="secondary">Amounts use each currency’s minor units. Add one row for every supported currency.</Typography.Paragraph><Form layout="vertical" initialValues={{ currencies: initial as CurrencyLimit[] }} onFinish={(values: { currencies: CurrencyLimit[] }) => onSave(values.currencies ?? [])}><Form.List name="currencies">{(fields, { add, remove }) => <><Space direction="vertical" style={{ width: '100%' }}>{fields.map((field) => <Space key={field.key} wrap align="start"><Form.Item label="Currency" name={[field.name, 'currency']} rules={[{ required: true }]}><Select style={{ width: 120 }} showSearch options={(currencies.data ?? []).map((currency) => ({ value: currency.code, label: currency.code }))} /></Form.Item><Form.Item label="Min bet" name={[field.name, 'bet_min']} rules={[{ required: true }]}><InputNumber min={1} /></Form.Item><Form.Item label="Max bet" name={[field.name, 'bet_max']} rules={[{ required: true }]}><InputNumber min={1} /></Form.Item><Form.Item label="Default bet" name={[field.name, 'bet_default']} rules={[{ required: true }]}><InputNumber min={1} /></Form.Item><Form.Item label="Step" name={[field.name, 'bet_step']}><InputNumber min={0} /></Form.Item><Button danger onClick={() => remove(field.name)}>Remove</Button></Space>)}</Space><Button onClick={() => add({ bet_step: 0 })}>Add currency limit</Button></>}</Form.List><Button type="primary" htmlType="submit">Save currency limits</Button></Form></>;
}

type BetLevel = { level: number; bet_amount: number };
function BetLevelsForm({ initial, onSave }: { initial: unknown; onSave: (levels: BetLevel[]) => void }) { return <><Typography.Title level={4}>Bet levels</Typography.Title><Typography.Paragraph type="secondary">Levels must be consecutive and each stake must be larger than the preceding one.</Typography.Paragraph><Form layout="vertical" initialValues={{ bet_levels: initial as BetLevel[] }} onFinish={(values: { bet_levels: BetLevel[] }) => onSave(values.bet_levels ?? [])}><Form.List name="bet_levels">{(fields, { add, remove }) => <><Space direction="vertical" style={{ width: '100%' }}>{fields.map((field) => <Space key={field.key} align="start"><Form.Item label="Level" name={[field.name, 'level']} rules={[{ required: true }]}><InputNumber min={1} /></Form.Item><Form.Item label="Bet amount" name={[field.name, 'bet_amount']} rules={[{ required: true }]}><InputNumber min={1} /></Form.Item><Button danger onClick={() => remove(field.name)}>Remove</Button></Space>)}</Space><Button onClick={() => add({ level: fields.length + 1 })}>Add bet level</Button></>}</Form.List><Button type="primary" htmlType="submit">Save bet levels</Button></Form></>; }

type WinThreshold = { code: string; multiplier: number };
function WinThresholdsForm({ initial, onSave }: { initial: unknown; onSave: (thresholds: WinThreshold[]) => void }) { return <><Typography.Title level={4}>Win thresholds</Typography.Title><Typography.Paragraph type="secondary">Use a short lowercase code and the win multiplier at which it applies.</Typography.Paragraph><Form layout="vertical" initialValues={{ win_thresholds: initial as WinThreshold[] }} onFinish={(values: { win_thresholds: WinThreshold[] }) => onSave(values.win_thresholds ?? [])}><Form.List name="win_thresholds">{(fields, { add, remove }) => <><Space direction="vertical" style={{ width: '100%' }}>{fields.map((field) => <Space key={field.key} align="start"><Form.Item label="Code" name={[field.name, 'code']} rules={[{ required: true, pattern: /^[a-z][a-z0-9_]{1,31}$/ }]}><Input placeholder="e.g. major_win" /></Form.Item><Form.Item label="Multiplier" name={[field.name, 'multiplier']} rules={[{ required: true }]}><InputNumber min={0.01} step={0.01} /></Form.Item><Button danger onClick={() => remove(field.name)}>Remove</Button></Space>)}</Space><Button onClick={() => add()}>Add win threshold</Button></>}</Form.List><Button type="primary" htmlType="submit">Save win thresholds</Button></Form></>; }

type ReportFilters = { from: string; to: string; tz?: string; granularity?: string; group_by?: string[] };
function dates(): Pick<ReportFilters, 'from' | 'to'> { const today = new Date(); const to = today.toISOString().slice(0, 10); const from = new Date(today.getTime() - 6 * 86_400_000).toISOString().slice(0, 10); return { from, to }; }
export function AnalyticsPage() {
  const { scopePath, me } = useAdminScope(); const [filters, setFilters] = useState<ReportFilters>({ ...dates(), granularity: 'day', group_by: ['date'] });
  const summary = useQuery({ queryKey: ['analytics-summary', scopePath, filters.from, filters.to, filters.tz], queryFn: () => read<AnalyticsSummary>(`${scopePath}/analytics/summary?${new URLSearchParams({ from: filters.from, to: filters.to, ...(filters.tz ? { tz: filters.tz } : {}) })}`), enabled: Boolean(me.data) });
  const series = useQuery({ queryKey: ['analytics-timeseries', scopePath, filters], queryFn: () => read<TimeseriesPoint[]>(`${scopePath}/analytics/timeseries?${new URLSearchParams({ from: filters.from, to: filters.to, granularity: filters.granularity ?? 'day' })}`), enabled: Boolean(me.data) });
  const ggr = useQuery({ queryKey: ['ggr', scopePath, filters.from, filters.to], queryFn: () => list<Record<string, unknown>>(`${scopePath}/reports/ggr`, { from: filters.from, to: filters.to, group_by: filters.group_by }), enabled: Boolean(me.data) });
  const ggrColumns = useMemo<ColumnsType<Record<string, unknown>>>(() => { const first = ggr.data?.items[0]; return first ? Object.keys(first).map((key) => ({ title: key.replace(/_/g, ' '), dataIndex: key, render: (value) => String(value ?? '—') })) : []; }, [ggr.data]);
  return <AdminPage title="Analytics"><Form layout="inline" initialValues={filters} onFinish={(values: ReportFilters) => setFilters(values)}><Form.Item label="From" name="from"><Input type="date" /></Form.Item><Form.Item label="To" name="to"><Input type="date" /></Form.Item><Form.Item label="Granularity" name="granularity"><Select style={{ width: 120 }} options={['hour', 'day', 'week', 'month'].map((value) => ({ value }))} /></Form.Item><Button type="primary" htmlType="submit">Apply</Button></Form>{summary.isError ? <Alert type="error" message="Unable to load analytics." /> : <Space direction="vertical" size="large" style={{ width: '100%' }}><Typography.Title level={4}>Summary by currency</Typography.Title><Table rowKey={(row) => String(row.currency)} loading={summary.isLoading} pagination={false} dataSource={summary.data?.currencies ?? []} columns={summary.data?.currencies.length ? Object.keys(summary.data.currencies[0]).map((key) => ({ title: key.replace(/_/g, ' '), dataIndex: key, render: (value) => String(value ?? '—') })) : []} /><Typography.Title level={4}>Time series</Typography.Title><Table rowKey="bucket" loading={series.isLoading} pagination={false} dataSource={series.data ?? []} columns={[{ title: 'Bucket', dataIndex: 'bucket' }, { title: 'Currencies', render: (_, row) => row.currencies.map((currency) => JSON.stringify(currency)).join(' · ') }]} /><Typography.Title level={4}>GGR report</Typography.Title><ServerTable page={ggr.data} loading={ggr.isLoading} error={ggr.error} columns={ggrColumns} /></Space>}</AdminPage>;
}

export function AuditPage() {
  const { scopePath, me } = useAdminScope(); const [filters, setFilters] = useState({ action: '', entity_type: '', from: '', to: '' }); const query = useQuery({ queryKey: ['audit', scopePath, filters], queryFn: () => list<AuditEntry>(`${scopePath}/audit`, filters), enabled: Boolean(me.data) });
  const columns: ColumnsType<AuditEntry> = [{ title: 'When', dataIndex: 'occurred_at' }, { title: 'Action', dataIndex: 'action' }, { title: 'Actor', render: (_, row) => row.actor?.name ?? 'System' }, { title: 'Entity', render: (_, row) => row.entity_type ? `${row.entity_type}: ${row.entity_id}` : '—' }, { title: 'Operator', dataIndex: 'operator_uuid' }];
  return <AdminPage title="Audit log"><Form layout="inline" initialValues={filters} onFinish={setFilters}><Form.Item label="Action" name="action"><Input /></Form.Item><Form.Item label="Entity" name="entity_type"><Input /></Form.Item><Form.Item label="From" name="from"><Input type="date" /></Form.Item><Form.Item label="To" name="to"><Input type="date" /></Form.Item><Button type="primary" htmlType="submit">Filter</Button></Form><ServerTable page={query.data} loading={query.isLoading} error={query.error} columns={columns} /></AdminPage>;
}
